export const PRODUCTS = [
  {
    id: "p1",
    name: "ProBook X15",
    category: "Laptops",
    price: 39999,
    originalPrice: 45999,
    description: "High-performance laptop for professionals.",
    imageColor: "from-blue-800 to-slate-900",
    rating: 4.7,
    reviewCount: 238,
  },
  {
    id: "p2",
    name: "UltraSlim 13",
    category: "Laptops",
    price: 52999,
    description: "Lightweight and powerful ultrabook.",
    imageColor: "from-slate-700 to-slate-900",
    rating: 4.5,
    reviewCount: 154,
  },
  {
    id: "p3",
    name: "Vertex Nova 5G",
    category: "Phones",
    price: 24999,
    originalPrice: 28999,
    description: "Flagship 5G smartphone with incredible camera.",
    imageColor: "from-indigo-800 to-slate-800",
    rating: 4.8,
    reviewCount: 412,
  },
  {
    id: "p4",
    name: "Summit Pro",
    category: "Phones",
    price: 18999,
    description: "Solid performance at a mid-range price.",
    imageColor: "from-slate-800 to-zinc-900",
    rating: 4.2,
    reviewCount: 189,
  },
  {
    id: "p5",
    name: "Vertex Pad 10",
    category: "Tablets",
    price: 13499,
    originalPrice: 15999,
    description: "10-inch tablet for entertainment and productivity.",
    imageColor: "from-blue-900 to-indigo-900",
    rating: 4.4,
    reviewCount: 97,
  },
  {
    id: "p6",
    name: "USB-C Hub",
    category: "Accessories",
    price: 1299,
    description: "Expand your connectivity options.",
    imageColor: "from-gray-700 to-gray-900",
    rating: 4.3,
    reviewCount: 322,
  },
  {
    id: "p7",
    name: "Wireless Mouse",
    category: "Accessories",
    price: 699,
    originalPrice: 899,
    description: "Ergonomic wireless mouse with precision tracking.",
    imageColor: "from-slate-600 to-slate-800",
    rating: 4.1,
    reviewCount: 275,
  },
  {
    id: "p8",
    name: "BassCore Earbuds",
    category: "Audio",
    price: 1999,
    originalPrice: 2499,
    description: "True wireless earbuds with deep bass.",
    imageColor: "from-zinc-800 to-black",
    rating: 4.6,
    reviewCount: 503,
  },
  {
    id: "p9",
    name: "NoiseBlock Headset",
    category: "Audio",
    price: 4999,
    description: "Active noise cancelling over-ear headphones.",
    imageColor: "from-gray-800 to-neutral-900",
    rating: 4.5,
    reviewCount: 168,
  },
  {
    id: "p10",
    name: "PowerBrick 20000",
    category: "Accessories",
    price: 1599,
    description: "High-capacity power bank.",
    imageColor: "from-slate-800 to-slate-900",
    rating: 4.3,
    reviewCount: 441,
  },
  {
    id: "p11",
    name: "DevBook 16",
    category: "Laptops",
    price: 85999,
    description: "The ultimate machine for developers.",
    imageColor: "from-neutral-800 to-black",
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: "p12",
    name: "Vertex Mini",
    category: "Phones",
    price: 15999,
    description: "Compact size, full power.",
    imageColor: "from-blue-700 to-blue-900",
    rating: 4.0,
    reviewCount: 213,
  },
  {
    id: "p13",
    name: "Gamer Elite 15",
    category: "Laptops",
    price: 65999,
    originalPrice: 72999,
    description: "High refresh rate screen and dedicated GPU.",
    imageColor: "from-red-900 to-black",
    rating: 4.7,
    reviewCount: 196,
  },
  {
    id: "p14",
    name: "SoundPod Bluetooth Speaker",
    category: "Audio",
    price: 2999,
    description: "Portable waterproof speaker.",
    imageColor: "from-indigo-900 to-black",
    rating: 4.4,
    reviewCount: 329,
  },
  {
    id: "p15",
    name: "Mechanical Keyboard X1",
    category: "Accessories",
    price: 3499,
    originalPrice: 4299,
    description: "Tactile mechanical switches for fast typing.",
    imageColor: "from-slate-700 to-neutral-800",
    rating: 4.6,
    reviewCount: 258,
  },
  {
    id: "p16",
    name: "Vertex Pad 12 Pro",
    category: "Tablets",
    price: 25999,
    description: "Large screen tablet for creative professionals.",
    imageColor: "from-blue-900 to-slate-900",
    rating: 4.5,
    reviewCount: 74,
  },
  {
    id: "p17",
    name: "UltraCharge Cable",
    category: "Accessories",
    price: 399,
    description: "Braided fast charging USB-C cable.",
    imageColor: "from-gray-600 to-gray-800",
    rating: 4.2,
    reviewCount: 688,
  },
  {
    id: "p18",
    name: "Studio Mic Pro",
    category: "Audio",
    price: 5499,
    description: "USB condenser microphone for streaming.",
    imageColor: "from-neutral-800 to-zinc-900",
    rating: 4.7,
    reviewCount: 112,
  },
  {
    id: "p19",
    name: "Vertex Fold",
    category: "Phones",
    price: 55999,
    description: "Next generation folding smartphone.",
    imageColor: "from-slate-900 to-black",
    rating: 4.3,
    reviewCount: 56,
  },
  {
    id: "p20",
    name: "Laptop Stand Aluminum",
    category: "Accessories",
    price: 1199,
    description: "Ergonomic foldable laptop stand.",
    imageColor: "from-gray-500 to-gray-700",
    rating: 4.4,
    reviewCount: 374,
  },
  {
    id: "p21",
    name: "Creator Display 27",
    category: "Accessories",
    price: 18999,
    originalPrice: 21999,
    description: "Color-accurate 4K monitor.",
    imageColor: "from-indigo-900 to-blue-900",
    rating: 4.8,
    reviewCount: 143,
  },
  {
    id: "p22",
    name: "Webcam HD 1080p",
    category: "Accessories",
    price: 2299,
    description: "Crystal clear video calls.",
    imageColor: "from-slate-700 to-slate-900",
    rating: 4.1,
    reviewCount: 209,
  },
  {
    id: "p23",
    name: "Vertex Earbuds Lite",
    category: "Audio",
    price: 1299,
    description: "Affordable wireless listening.",
    imageColor: "from-zinc-700 to-zinc-900",
    rating: 3.9,
    reviewCount: 481,
  },
  {
    id: "p24",
    name: "SmartTag Tracker",
    category: "Accessories",
    price: 899,
    description: "Never lose your keys again.",
    imageColor: "from-blue-800 to-indigo-900",
    rating: 4.2,
    reviewCount: 317,
  },
];
